# Generated by Django 4.0.1 on 2022-02-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='market',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='ingredient.market'),
            preserve_default=False,
        ),
    ]
