# Generated by Django 4.0.1 on 2022-02-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_alter_ingredient_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.market'),
        ),
    ]
