# Generated by Django 4.0.1 on 2022-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0006_alter_ingredient_market'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'market'), name='unique_ingredient_name'),
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
    ]
