# Generated by Django 4.0.1 on 2022-02-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_ingredient_unique_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
    ]
