# Generated by Django 4.0.1 on 2022-02-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0009_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_name',
        ),
    ]
