# Generated by Django 4.0.1 on 2022-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0010_remove_ingredient_unique_ingredient_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'market'), name='unique_ingredient_name'),
        ),
    ]
