# Generated by Django 4.0.1 on 2022-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_alter_inventoryingredient_ingredient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'pantry'), name='unique_ingredient_pantry'),
        ),
    ]
